In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy
from scipy import stats

In [19]:
df=pd.read_csv('BuyerRatio.csv')
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [20]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [22]:
df1=df.iloc[:,1:6]
df1

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [23]:
df1.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [24]:
df2=stats.chi2_contingency(df1)

In [25]:
df2

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [27]:
no_of_row=len(df1.iloc[0:2,0])
no_of_columns=len(df1.iloc[0,0:4])
degreed_of_f=(no_of_row-1)*(no_of_columns-1)
print('Degrees_of_Freedom=',degreed_of_f)

Degrees_of_Freedom= 3


In [31]:
value=df2[3]

In [32]:
value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [33]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df1.values,value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [34]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [35]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [36]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [37]:
if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)
